name: GitHub-Actions

on: 
  push:
    branches:
      - main
jobs:
  print_1:
    runs-on: ubuntu-latest

    steps:
    - name: print hello
      run: echo "hello world"
  print_2:
    runs-on: ubuntu-latest

    steps:
    - name: print hello
      run: echo "hello world"
